common: &common
  google_api_key: ABQIAAAAdJDpHOm2ScdjgUWKqN4KjBQaCoiz7kHbPYNoCNHTGcAwLJhMgBR8qrqyrFXo1Mjrdp3x6JTugklIXQ
  yahoo_api_key: vmp3df7V34F7vuDzFsuuyNMOP7LIFR9L8yK_eE_tfVbTYALA0B3SLFv4aWgf00wE3aLkCfCxag--
  verbose_logging: false
  
production:
  <<: *common

development:
  <<: *common
  verbose_logging: true

test:
  <<: *common
  verbose_logging: true
